import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#4edea3",
        "inverse-surface": "#283044",
        "on-secondary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-highest": "#dae2fd",
        "error-container": "#ffdad6",
        "on-surface": "#131b2e",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "inverse-primary": "#b4c5ff",
        "secondary-fixed": "#6ffbbe",
        "on-surface-variant": "#434655",
        "on-tertiary-fixed": "#07006c",
        "inverse-on-surface": "#eef0ff",
        "tertiary-container": "#585be6",
        "on-error-container": "#93000a",
        "on-primary-container": "#eeefff",
        "surface-bright": "#faf8ff",
        tertiary: "#3e3fcc",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed-variant": "#005236",
        error: "#ba1a1a",
        outline: "#737686",
        surface: "#faf8ff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        primary: "#004ac6",
        "on-error": "#ffffff",
        background: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "on-tertiary-container": "#f1eeff",
        "surface-container": "#eaedff",
        "tertiary-fixed": "#e1e0ff",
        "on-secondary-container": "#00714d",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "primary-fixed": "#dbe1ff",
        secondary: "#006c49",
        "outline-variant": "#c3c6d7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "2rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        margin: "1rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        caption: ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        display: ["var(--font-inter)", "sans-serif"],
        "label-code": ["var(--font-jetbrains)", "monospace"],
        "label-code-sm": ["var(--font-jetbrains)", "monospace"],
      },
      fontSize: {
        display: ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-code-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
        caption: ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
